services:
  api:
    image: ${GHCR_IMAGE_PREFIX:-ghcr.io/tokkitomuichiro/-quipment-accounting}-api:${IMAGE_TAG:-latest}

  frontend:
    image: ${GHCR_IMAGE_PREFIX:-ghcr.io/tokkitomuichiro/-quipment-accounting}-frontend:${IMAGE_TAG:-latest}